service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

  environment:
    SQS_URL:
      Ref: SQSQueue
    SNS_ARN:
      Ref: SNSTopic
    PG_HOST: rs-aws-database.cy8ogj0gxkz1.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: rs_shop_db
    PG_USERNAME: postgres
    PG_PASSWORD: cVB2DZVr4axS2xicNWyG

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'sns:*'
          Resource:
            Ref: SNSTopic

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: createProductTopic
    SNSSubscriptions:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ray.zug@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic

functions:
  getProductsList:
    handler: handler.getProductsList
    events:
      - http:
          path: products
          method: get
          cors: true
  getProductsById:
    handler: handler.getProductsById
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true
  addProduct:
    handler: handler.addProduct
    events:
      - http:
          path: products
          method: post
          cors: true
  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - SQSQueue
              - Arn
#    Define function environment variables here
#    environment:
#      variable2: value2

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
